name: kbbi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  http: ^1.2.2
  awesome_notifications: ^0.10.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  workmanager: ^0.5.2
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
