class KataAcak {
  static final List<String> kataKata = [
    'abstrak',
    'akses',
    'analisis',
    'antarmuka',
    'aplikasi',
    'arsitektur',
    'basis data',
    'cache',
    'debug',
    'enkripsi',
    'implementasi',
    'kompilasi',
    'koneksi',
    'kriptografi',
    'memori',
    'optimasi',
    'pemrograman',
    'protokol',
    'sinkronisasi',
    'transaksi',
    'virtualisasi',
    'alinea',
    'gerhana',
    'hibrida',
    'klorofil',
    'kontaminasi',
    'metafora',
    'neologisme',
    'paradigma',
    'sinergi',
    'teori',
    'vokasional',
    'abdikasi',
    'adendum',
    'ambivalensi',
    'anodisasi',
    'balistik',
    'deduksi',
    'eksentrik',
    'idiosinkrasi',
    'konvergensi',
    'paradoks',
    'replikasi',
    'tropisme',
    'utopis',
    'xenofobia',
  ];

  static String getKataAcak() {
    kataKata.shuffle();
    return kataKata.first;
  }
}
